---
title: "Praca tydzień 1 - Wykresy"
author: "Jan Staszak"
format: gfm
editor: visual
---

## Dane:

```{r}
#| message: false
#| warning: false
#| include: false
#biblioteki
library(ggplot2)
library(cowplot)
#wczytanie danych
data0.3 <- read.csv("C:\\Users\\Admin\\Desktop\\Praca_Magisterska\\Wykresy_wyjsciowe\\0.3mg plot-data full.csv", header=TRUE, stringsAsFactors=FALSE)
data3.0 <- read.csv("C:\\Users\\Admin\\Desktop\\Praca_Magisterska\\Wykresy_wyjsciowe\\3.0mg plot-data full.csv",  header=TRUE, stringsAsFactors=FALSE)
data15.0 <- read.csv("C:\\Users\\Admin\\Desktop\\Praca_Magisterska\\Wykresy_wyjsciowe\\15.0mg plot-data full.csv", header=TRUE, stringsAsFactors=FALSE)
data30.0 <- read.csv("C:\\Users\\Admin\\Desktop\\Praca_Magisterska\\Wykresy_wyjsciowe\\30.0mg plot-data full.csv",  header=TRUE, stringsAsFactors=FALSE)
dataAUC <- read.csv("C:\\Users\\Admin\\Desktop\\Praca_Magisterska\\Wykresy_wyjsciowe\\AUC.csv", 
                     header=TRUE, stringsAsFactors=FALSE)
dataCmax <- read.csv("C:\\Users\\Admin\\Desktop\\Praca_Magisterska\\Wykresy_wyjsciowe\\Cmax.csv", 
                    header=TRUE, stringsAsFactors=FALSE)
str(data0.3)
str(data3.0)
str(data15.0)
str(data30.0)
str(dataAUC)
str(dataCmax)
```

```{r}
#| echo: false
print('Dose 0.3')
data0.3
print('Dose 3.0')
data3.0
print('Dose 15.0')
data15.0
print('Dose 30.0')
data30.0
print('AUC(D)')
dataAUC
'Cmax(D)'
dataCmax
```

## Wykresy:

Kod C(t):

```{r}
#| echo: true
#| message: false
#| warning: false
options(scipen=999)

plot0.3<- ggplot()+
  geom_line(data=data0.3, mapping = aes(x=Time, y=MotaC, col='Motavizumab'))+
  geom_line(data=data0.3, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'))+
  geom_point(data=data0.3, mapping = aes(x=Time, y=MotaC, col="Motavizumab"), 
             size=2.5)+
  geom_point(data=data0.3, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'), size=2.5)+
  scale_y_log10()+ coord_cartesian(xlim=c(0,245), ylim = c(0.25,10))+
  labs(title="Serum Concentration vs Time", subtitle = "Dose: 0.3 mg/kg", 
       y="Serum Concentration [mug/ml]", x="Time [d]")+ scale_x_continuous(breaks=seq(0, 245, 28))+
  scale_color_manual(name='Substance', breaks = c("Motavizumab", "Mota-YTE"), 
       values = c("Motavizumab"="firebrick3","Mota-YTE"="dodgerblue3"))+
  theme(legend.title = element_text(size=12, color = "black", face="bold"),
          legend.justification=c(1,0),legend.position=c(0.95, 0.65))

plot3.0<- ggplot()+
  geom_line(data=data3.0, mapping = aes(x=Time, y=MotaC, col='Motavizumab'))+
  geom_line(data=data3.0, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'))+
  geom_point(data=data3.0, mapping = aes(x=Time, y=MotaC, col="Motavizumab"), size=2.5)+
  geom_point(data=data3.0, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'), size=2.5)+
  scale_y_log10()+ coord_cartesian(xlim=c(0,245), ylim = c(1.5,100))+
  labs(title="Serum Concentration vs Time", subtitle = "Dose: 3.0 mg/kg", 
       y="Serum Concentration [mug/ml]", x="Time [d]")+ scale_x_continuous(breaks=seq(0, 245, 28))+
  scale_color_manual(name='Substance', breaks = c("Motavizumab", "Mota-YTE"), 
                     values = c("Motavizumab"="firebrick3","Mota-YTE"="dodgerblue3"))+
  theme(legend.title = element_text(size=12, color = "black", face="bold"),
        legend.justification=c(1,0),legend.position=c(0.95, 0.65))

plot15.0<- ggplot()+
  geom_line(data=data15.0, mapping = aes(x=Time, y=MotaC, col='Motavizumab'))+
  geom_line(data=data15.0, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'))+
  geom_point(data=data15.0, mapping = aes(x=Time, y=MotaC, col="Motavizumab"), size=2.5)+
  geom_point(data=data15.0, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'), size=2.5)+
  scale_y_log10()+ coord_cartesian(xlim=c(0,245), ylim = c(4,400))+
  labs(title="Serum Concentration vs Time", subtitle = "Dose: 15.0 mg/kg", 
       y="Serum Concentration [mug/ml]", x="Time [d]")+ scale_x_continuous(breaks=seq(0, 245, 28))+
  scale_color_manual(name='Substance', breaks = c("Motavizumab", "Mota-YTE"), 
                     values = c("Motavizumab"="firebrick3","Mota-YTE"="dodgerblue3"))+
  theme(legend.title = element_text(size=12, color = "black", face="bold"),
        legend.justification=c(1,0),legend.position=c(0.95, 0.65))

plot30.0<- ggplot()+
  geom_line(data=data30.0, mapping = aes(x=Time, y=MotaC, col='Motavizumab'))+
  geom_line(data=data30.0, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'))+
  geom_point(data=data30.0, mapping = aes(x=Time, y=MotaC, col="Motavizumab"), size=2.5)+
  geom_point(data=data30.0, mapping= aes(x=Time, y=YTEC, col='Mota-YTE'), size=2.5)+
  scale_y_log10()+ coord_cartesian(xlim=c(0,245), ylim = c(2,1000))+
  labs(title="Serum Concentration vs Time", subtitle = "Dose: 30.0 mg/kg", 
       y="Serum Concentration [mug/ml]", x="Time [d]")+ scale_x_continuous(breaks=seq(0, 245, 28))+
  scale_color_manual(name='Substance', breaks = c("Motavizumab", "Mota-YTE"), 
                     values = c("Motavizumab"="firebrick3","Mota-YTE"="dodgerblue3"))+
  theme(legend.title = element_text(size=12, color = "black", face="bold"),
        legend.justification=c(1,0),legend.position=c(0.95, 0.65))
```

Wykresy C(t):

```{r}
#| message: false
#| warning: false
combined_plot <- plot_grid(plot0.3, plot3.0, plot15.0, plot30.0)
combined_plot
```

Kod AUC(D) i Cmax(D):

```{r}
#| message: false
#| warning: false
plotAUC<-ggplot()+geom_point(data=dataAUC, mapping = aes(x=Dose, y=AUCMota, col='Motavizumab'))+
  geom_point(data=dataAUC, mapping = aes(x=Dose, y=AUCYTE, col='Mota-YTE'))+
  geom_errorbar(data=dataAUC, aes(Dose, ymin=AUCYTE-CVYTE*AUCYTE*0.5, ymax=AUCYTE+CVYTE*AUCYTE*0.5, col='Mota-YTE'), width=0.3)+
  geom_errorbar(data=dataAUC, aes(Dose, ymin=AUCMota-CVMota*AUCMota*0.5, ymax=AUCMota+CVMota*AUCMota*0.5, col='Motavizumab'), width=0.3)+
  geom_smooth(data=dataAUC,mapping = aes(x=Dose, y=AUCMota), method=lm, se=FALSE, col='firebrick4', size=1)+
  geom_smooth(data=dataAUC,mapping = aes(x=Dose, y=AUCYTE), method=lm, se=FALSE, col='dodgerblue4', size=1)+
  labs(title="AUC(D)", y="AUC [μg · day/ml]", x="Dose [mg/kg]")+
  scale_color_manual(name='Substance', breaks = c("Motavizumab", "Mota-YTE"),values = c("Motavizumab"="firebrick3","Mota-YTE"="dodgerblue3"))+
  theme(legend.title = element_text(size=12, color = "black", face="bold"),
        legend.justification=c(1,0),legend.position=c(0.20, 0.45))+
  coord_cartesian(xlim=c(0,30), ylim = c(0,52500))

plotCmax<-ggplot()+geom_point(data=dataCmax, mapping = aes(x=Dose, y=CmaxMota, col='Motavizumab'))+
  geom_point(data=dataCmax, mapping = aes(x=Dose, y=CmaxYTE, col='Mota-YTE'))+
  geom_errorbar(data=dataCmax, aes(Dose, ymin=CmaxYTE-CVYTE*CmaxYTE*0.5, ymax=CmaxYTE+CVYTE*CmaxYTE*0.5, col='Mota-YTE'), width=0.3)+
  geom_errorbar(data=dataCmax, aes(Dose, ymin=CmaxMota-CVMota*CmaxMota*0.5, ymax=CmaxMota+CVMota*CmaxMota*0.5, col='Motavizumab'), width=0.3)+
  geom_smooth(data=dataCmax,mapping = aes(x=Dose, y=CmaxMota), method=lm, se=FALSE, col='firebrick4', size=1)+
  geom_smooth(data=dataCmax,mapping = aes(x=Dose, y=CmaxYTE), method=lm, se=FALSE, col='dodgerblue4', size=1)+
  labs(title="Cmax(D)", y="Maximum Concentration [μg/ml]", x="Dose [mg/kg]")+
  scale_color_manual(name='Substance', breaks = c("Motavizumab", "Mota-YTE"),values = c("Motavizumab"="firebrick3","Mota-YTE"="dodgerblue3"))+
  theme(legend.title = element_text(size=12, color = "black", face="bold"),
        legend.justification=c(1,0),legend.position=c(0.20, 0.45))
```

Wykresy AUC(D) i Cmax(D):

```{r}
#| echo: false
#| message: false
#| warning: false
CmaxAUC <- plot_grid(plotAUC, plotCmax, nrow = 2)
CmaxAUC
```
